### ISSUE TITLE
fast-csv is not installed when following directions in tutorial

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb-tutorials#48]
```shell
gavin@titan:~/dev/tt/getting_started$ node javascript-client/insert_data.js 
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fast-csv'
Require stack:
- /home/gavin/dev/tt/getting_started/javascript-client/insert_data.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gavin/dev/tt/getting_started/javascript-client/insert_data.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/gavin/dev/tt/getting_started/javascript-client/insert_data.js'
  ]
}
```

**Comment by Neelterminusdb** [comment]
Oh you are directly running the script. There is a step at first which is used to install the fast-csv package can you try that ?
