### ISSUE TITLE
getting_started/javascript-client/lesson_2 failed

### ISSUE THREAD

**Issue by layanto** [terminusdb/terminusdb-tutorials#70]
```
[]
Error: API Error @type api:InsertDocumentErrorResponse api:message Schema check failure api:status api:failure Code: 400 url: https://cloud.terminusdb.com/orgname/api/document/teamname/GettingStartedDB/local/branch/main
    at Object.apiErrorFormatted (C:\Projects\terminusx\node_modules\@terminusdb\terminusdb-client\lib\errorMessage.js:95:13)
    at C:\Projects\terminusx\node_modules\@terminusdb\terminusdb-client\lib\dispatchRequest.js:210:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  data: {
    '@type': 'api:InsertDocumentErrorResponse',
    'api:error': { '@type': 'api:SchemaCheckFailure', 'api:witnesses': [
  {
    '@type': 'unknown_property_for_type',
    document: {
      '@type': 'terminusdb:///schema#Employee',
      'terminusdb:///schema#address': [Object],
      'terminusdb:///schema#contact_number': '(01986) 113367',
      'terminusdb:///schema#employee_id': '001',
      'terminusdb:///schema#name': 'Destiny Norris',
      'terminusdb:///schema#team': 'Marketing',
      'terminusdb:///schema#title': 'Marketing Manager'
    },
    property: [ 'terminusdb:///schema#employee_id' ],
    type: 'terminusdb:///schema#Employee'
  }
] },
    'api:message': 'Schema check failure',
    'api:status': 'api:failure'
  },
  status: 400
}
```

**Comment by layanto** [comment]
Found the issue. The schema.js full content described in lesson_1 does not match the schema.js in the repo.
